FROM apache/airflow:2.9.3-python3.11
USER root


# Install java also
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         openjdk-17-jre-headless \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow


# Set up JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64


# Set YARN_CONF_DIR and HADOOP_CONF_DIR
ENV YARN_CONF_DIR=/etc/hadoop
ENV HADOOP_CONF_DIR=/etc/hadoop

# Copy Hadoop configuration files
COPY --chown=airflow config/*.xml $HADOOP_CONF_DIR/

# Set YARN_CONF_DIR and HADOOP_CONF_DIR
ENV YARN_CONF_DIR=/etc/hadoop
ENV HADOOP_CONF_DIR=/etc/hadoop

#   Install requirements.txt
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
USER airflow