version: '3'
services:
  clickhouse-db:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
      - ./clickhouse/config/ports.xml:/etc/clickhouse-server/config.d/ports.xml
    ports:
      - "9876:9876"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1